"""empty message

Revision ID: 579aab2303aa
Revises: 9e808636afe7
Create Date: 2018-03-03 06:31:15.592725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '579aab2303aa'
down_revision = '9e808636afe7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'password')
    # ### end Alembic commands ###
